services:
  cyrene:
    container_name: "Cyrene"
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/willi/hosting/monifactory/data/logs/:/app/mc_logs
    depends_on:
      db:
        condition: service_healthy
    network_mode: service:tailscale

  tailscale:
    image: tailscale/tailscale
    container_name: cyrene_tailscale
    env_file: .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:cyrene --netfilter-mode=off
      - TS_HOSTNAME=cyrene
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  db:
    image: postgres:14.13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Cyrene
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  db:
    driver: local
